#Time Zone
time_zone: Australia/Sydney
cloud_host: "XXX.XXX.XXX.XXX"  # Replace with the actual IP address of your cloud server

# ~~~ PostgreSQL database info ~~~
postgresql_version: 14
cloud_database_name: "sensors"
cloud_database_user: "admin"
timescaledb_version: "2"  # Replace with the desired TimescaleDB version

# mosquitto
mqtt_username: "admin"

#node red
nodered_user: "admin"
node_red_palettes:
  - node-red-dashboard
  - node-red-contrib-msg-resend
  - node-red-contrib-isonline
  - node-red-contrib-postgresql

#nginx
domain_name: "example.com"
email: "cert.managers@example.com"